apiVersion: v1
kind: Service
metadata:
  name: similarity-service
  labels:
    app: api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: api
